package com.zdk.pojo;

import com.zdk.pojo.base.BaseStudent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Student extends BaseStudent<Student> {
	private int id;
	private String name;
	private int tid;
}
